sudo: required #require super user
services:
  - docker #require a copy of docker

before_install: #what needs to be done before project run
  - docker build -t phuaweijie/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true phuaweijie/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-102097092766"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
